# Generated by Django 4.2.5 on 2025-02-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerCondition', models.CharField(blank=True, max_length=50, null=True)),
                ('offerDescription', models.TextField(blank=True, null=True)),
                ('sellerProductItemId', models.BigIntegerField(blank=True, null=True)),
                ('vendorItemId', models.BigIntegerField(blank=True, null=True)),
                ('itemId', models.BigIntegerField(blank=True, null=True)),
                ('itemName', models.CharField(blank=True, max_length=255, null=True)),
                ('originalPrice', models.IntegerField(default=0)),
                ('salePrice', models.IntegerField(default=0)),
                ('supplyPrice', models.IntegerField(default=0)),
                ('maximumBuyCount', models.IntegerField(default=0)),
                ('maximumBuyForPerson', models.IntegerField(default=0)),
                ('outboundShippingTimeDay', models.IntegerField(default=0)),
                ('maximumBuyForPersonPeriod', models.IntegerField(default=0)),
                ('unitCount', models.IntegerField(default=1)),
                ('adultOnly', models.CharField(blank=True, max_length=50, null=True)),
                ('freePriceType', models.CharField(blank=True, max_length=50, null=True)),
                ('taxType', models.CharField(blank=True, max_length=50, null=True)),
                ('parallelImported', models.CharField(blank=True, max_length=50, null=True)),
                ('overseasPurchased', models.CharField(blank=True, max_length=50, null=True)),
                ('externalVendorSku', models.CharField(blank=True, max_length=100, null=True)),
                ('pccNeeded', models.BooleanField(default=False)),
                ('bestPriceGuaranteed3P', models.BooleanField(default=False)),
                ('emptyBarcode', models.BooleanField(default=False)),
                ('emptyBarcodeReason', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('saleAgentCommission', models.IntegerField(default=0)),
                ('modelNo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoupangItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('sellerProductId', models.BigIntegerField(blank=True, null=True)),
                ('sellerProductName', models.CharField(blank=True, max_length=255, null=True)),
                ('displayCategoryCode', models.BigIntegerField(blank=True, null=True)),
                ('categoryId', models.BigIntegerField(blank=True, null=True)),
                ('productId', models.BigIntegerField(blank=True, null=True)),
                ('vendorId', models.CharField(blank=True, max_length=50, null=True)),
                ('mdId', models.CharField(blank=True, max_length=50, null=True)),
                ('mdName', models.CharField(blank=True, max_length=50, null=True)),
                ('saleStartedAt', models.DateTimeField(blank=True, null=True)),
                ('saleEndedAt', models.DateTimeField(blank=True, null=True)),
                ('displayProductName', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('generalProductName', models.CharField(blank=True, max_length=255, null=True)),
                ('productGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('statusName', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryCompanyCode', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryChargeType', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryCharge', models.IntegerField(default=0)),
                ('freeShipOverAmount', models.IntegerField(default=0)),
                ('deliveryChargeOnReturn', models.IntegerField(default=0)),
                ('deliverySurcharge', models.IntegerField(default=0)),
                ('remoteAreaDeliverable', models.CharField(blank=True, max_length=1, null=True)),
                ('bundlePackingDelivery', models.IntegerField(default=0)),
                ('unionDeliveryType', models.CharField(blank=True, max_length=50, null=True)),
                ('returnCenterCode', models.CharField(blank=True, max_length=50, null=True)),
                ('returnChargeName', models.CharField(blank=True, max_length=255, null=True)),
                ('companyContactNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('returnZipCode', models.CharField(blank=True, max_length=20, null=True)),
                ('returnAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('returnAddressDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('returnCharge', models.IntegerField(default=0)),
                ('outboundShippingPlaceCode', models.BigIntegerField(blank=True, null=True)),
                ('vendorUserId', models.CharField(blank=True, max_length=100, null=True)),
                ('requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoupangItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOrder', models.IntegerField(default=0)),
                ('imageType', models.CharField(blank=True, max_length=50, null=True)),
                ('cdnPath', models.CharField(blank=True, max_length=255, null=True)),
                ('vendorPath', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coupang_sales.coupangitem')),
            ],
        ),
        migrations.AddField(
            model_name='coupangitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coupang_sales.coupangitemlist'),
        ),
    ]
