# Generated by Django 4.2.5 on 2025-02-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupang_sales', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_distribution_period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_expired_at_managed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_manufactured_at_managed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_original_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_quantity_per_box',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_sale_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_stand_alone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_supply_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
