# Generated by Django 4.2.5 on 2025-02-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupang_sales', '0004_alter_coupangitem_rocket_distribution_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupangitem',
            name='marketplace_maximum_buy_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupangitem',
            name='rocket_maximum_buy_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
