# Generated by Django 4.2.5 on 2025-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupang_sales', '0006_coupangitem_marketplace_external_vendor_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangitem',
            name='marketplace_external_vendor_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_external_vendor_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
