# Generated by Django 5.1.6 on 2025-03-05 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('channel', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('page_link', models.URLField(blank=True, null=True)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='상품명')),
                ('category', models.CharField(blank=True, choices=[('네이버', '네이버'), ('쿠팡', '쿠팡'), ('오늘의집', '오늘의집')], max_length=10, null=True, verbose_name='카테고리')),
                ('search_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='순위 조회 키워드')),
                ('single_product_link', models.URLField(blank=True, null=True, verbose_name='단일상품링크')),
                ('single_product_mid', models.CharField(blank=True, max_length=100, null=True, verbose_name='단일상품 MID값')),
                ('original_link', models.URLField(blank=True, default='', null=True, verbose_name='원부 링크')),
                ('original_mid', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='원부 MID')),
                ('store_name', models.CharField(default='', max_length=255, verbose_name='스토어명')),
                ('manager', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='담당자')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='트래픽명')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='금액')),
                ('method', models.CharField(choices=[('유입플', '유입플'), ('리워드', '리워드'), ('복합플', '복합플')], max_length=50, verbose_name='방식')),
                ('inflow_count', models.PositiveIntegerField(verbose_name='유입수')),
                ('link', models.URLField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('start_rank', models.IntegerField(blank=True, null=True)),
                ('yesterday_rank', models.IntegerField(blank=True, null=True)),
                ('current_rank', models.IntegerField(blank=True, null=True)),
                ('difference_rank', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='효과없음', max_length=20)),
                ('last_checked_date', models.DateTimeField(auto_now=True)),
                ('available_start_date', models.DateField()),
                ('available_end_date', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('ticket_count', models.IntegerField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_link', models.URLField(blank=True, null=True)),
                ('original_mid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('ending_rank', models.IntegerField(blank=True, null=True)),
                ('is_extended', models.BooleanField(default=False)),
                ('needs_attention', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management.keyword')),
                ('original_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_tasks', to='traffic_management.task')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_management.product')),
                ('traffic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_management.traffic')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('traffic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('traffic_count', models.IntegerField(default=0)),
                ('traffic_period', models.DateField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management.keyword')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='traffic_management.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('naver_client_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
