# Generated by Django 5.1.6 on 2025-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='단일,원부'),
        ),
    ]
