# Generated by Django 5.1.6 on 2025-03-09 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0008_rankingmonitoring_keywordranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordranking',
            name='update_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
