# Generated by Django 5.1.6 on 2025-03-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0011_rankingmonitoring_main_keyword1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordranking',
            name='is_original_better',
            field=models.BooleanField(default=False),
        ),
    ]
