# Generated by Django 5.1.6 on 2025-03-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0012_keywordranking_is_original_better'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordranking',
            name='update_at',
            field=models.DateField(),
        ),
    ]
