# Generated by Django 5.1.6 on 2025-03-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0013_alter_keywordranking_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordranking',
            name='update_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
