# Generated by Django 5.1.6 on 2025-03-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0014_alter_keywordranking_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navermarketingcost',
            old_name='product',
            new_name='task',
        ),
        migrations.AlterUniqueTogether(
            name='navermarketingcost',
            unique_together={('task', 'date')},
        ),
    ]