# Generated by Django 5.1.6 on 2025-03-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0014_alter_keywordranking_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverMarketingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('cost', models.DecimalField(max_digits=10, decimal_places=0, verbose_name='비용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='naver_costs',
                    to='traffic_management.Task',
                    verbose_name='작업'
                )),
            ],
            options={
                'unique_together': {('task', 'date')},
                'verbose_name': '네이버 마케팅 비용',
                'verbose_name_plural': '네이버 마케팅 비용',
            },
        ),
    ]


    
