# Generated by Django 5.1.6 on 2025-03-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0016_alter_navermarketingcost_unique_together_and_more'),
        ('traffic_management', '0018_merge_20250310_1614'),
        ('traffic_management', '0019_merge_20250310_1616'),
    ]

    operations = [
    ]
