# Generated by Django 5.1.6 on 2025-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0026_alter_keywordranking_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_mid',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='원부 MID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='single_product_mid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='단일상품 MID값'),
        ),
    ]
