# Generated by Django 5.1.6 on 2025-05-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0027_alter_product_original_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_mid',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='원부 MID'),
        ),
    ]
