# Generated by Django 5.1.6 on 2025-05-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0028_alter_product_original_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='single_product_mid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='단일상품 MID값'),
        ),
    ]
