# Generated by Django 5.1.3 on 2024-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupangAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('access_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NaverAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('claim_type', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('option_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('option_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_status', models.CharField(max_length=50)),
                ('claim_reason', models.CharField(max_length=200)),
                ('customer_reason', models.CharField(max_length=200)),
                ('return_shipping_charge', models.IntegerField(blank=True, null=True)),
                ('shipping_charge_payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('collect_tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('collect_delivery_company', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(default='미처리', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('product_issue', models.CharField(blank=True, choices=[('파손 및 불량', '파손 및 불량'), ('이상없음', '이상없음'), ('오배송', '오배송')], max_length=50, null=True)),
                ('order_number', models.CharField(max_length=50)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('claim_request_date', models.DateTimeField()),
                ('seller_product_item_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
