# Generated by Django 5.1.3 on 2024-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
