# Generated by Django 5.1.3 on 2024-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0002_returnitem_recipient_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='claim_reason',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='claim_status',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='customer_reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
