# Generated by Django 5.1.3 on 2024-12-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0004_alter_returnitem_claim_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='claim_type',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='inspector',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='option_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='option_name',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='processing_status',
            field=models.CharField(blank=True, default='미처리', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='product_issue',
            field=models.CharField(blank=True, choices=[('파손 및 불량', '파손 및 불량'), ('이상없음', '이상없음'), ('오배송', '오배송')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='product_name',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='recipient_contact',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='recipient_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='seller_product_item_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='shipping_charge_payment_method',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='store_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
