# Generated by Django 5.1.4 on 2024-12-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0007_returnitem_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='product_status',
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product_order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
