# Generated by Django 4.2.5 on 2024-12-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0008_remove_returnitem_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
