# Generated by Django 4.2.5 on 2024-12-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0010_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
