# Generated by Django 4.2.5 on 2025-02-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_management', '0002_remove_coupangitemimage_parent_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=255, null=True)),
                ('unitCount', models.IntegerField(default=1)),
                ('outboundShippingTime', models.IntegerField(default=0)),
                ('rocket_seller_product_item_id', models.BigIntegerField(blank=True, null=True)),
                ('rocket_vendor_item_id', models.BigIntegerField(blank=True, null=True)),
                ('rocket_item_id', models.BigIntegerField(blank=True, null=True)),
                ('rocket_barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('rocket_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rocket_original_price', models.IntegerField(default=0)),
                ('rocket_sale_price', models.IntegerField(default=0)),
                ('rocket_supply_price', models.IntegerField(default=0)),
                ('rocket_height', models.IntegerField(default=0)),
                ('rocket_length', models.IntegerField(default=0)),
                ('rocket_width', models.IntegerField(default=0)),
                ('rocket_weight', models.IntegerField(default=0)),
                ('rocket_quantity_per_box', models.IntegerField(default=1)),
                ('rocket_stand_alone', models.BooleanField(default=False)),
                ('rocket_distribution_period', models.IntegerField(default=0)),
                ('rocket_expired_at_managed', models.BooleanField(default=False)),
                ('rocket_manufactured_at_managed', models.BooleanField(default=False)),
                ('rocket_net_weight', models.IntegerField(blank=True, null=True)),
                ('rocket_heat_sensitive', models.BooleanField(blank=True, null=True)),
                ('rocket_hazardous', models.BooleanField(blank=True, null=True)),
                ('rocket_original_barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('rocket_inbound_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rocket_original_dimension_input_type', models.CharField(blank=True, max_length=50, null=True)),
                ('marketplace_seller_product_item_id', models.BigIntegerField(blank=True, null=True)),
                ('marketplace_vendor_item_id', models.BigIntegerField(blank=True, null=True)),
                ('marketplace_item_id', models.BigIntegerField(blank=True, null=True)),
                ('marketplace_barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('marketplace_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('marketplace_original_price', models.IntegerField(default=0)),
                ('marketplace_sale_price', models.IntegerField(default=0)),
                ('marketplace_supply_price', models.IntegerField(default=0)),
                ('marketplace_best_price_guaranteed_3p', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoupangProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('sellerProductId', models.BigIntegerField(blank=True, null=True)),
                ('sellerProductName', models.CharField(blank=True, max_length=255, null=True)),
                ('displayCategoryCode', models.BigIntegerField(blank=True, null=True)),
                ('vendorId', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('productGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('statusName', models.CharField(blank=True, max_length=50, null=True)),
                ('vendorUserId', models.CharField(blank=True, max_length=100, null=True)),
                ('requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoupangItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOrder', models.IntegerField(default=0)),
                ('imageType', models.CharField(blank=True, max_length=50, null=True)),
                ('cdnPath', models.CharField(blank=True, max_length=255, null=True)),
                ('vendorPath', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales_management.coupangitem')),
            ],
        ),
        migrations.AddField(
            model_name='coupangitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_management.coupangproduct'),
        ),
    ]
