# Generated by Django 4.2.5 on 2025-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0007_alter_coupangitem_marketplace_external_vendor_sku_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupangitem',
            constraint=models.UniqueConstraint(condition=models.Q(('rocket_vendor_item_id__isnull', False)), fields=('rocket_vendor_item_id',), name='unique_rocket_vendor_item_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='coupangitem',
            constraint=models.UniqueConstraint(condition=models.Q(('marketplace_vendor_item_id__isnull', False)), fields=('marketplace_vendor_item_id',), name='unique_market_vendor_item_id_not_null'),
        ),
    ]
