# Generated by Django 4.2.5 on 2025-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0008_coupangitem_unique_rocket_vendor_item_id_not_null_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupangproduct',
            name='categoryId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupangproduct',
            name='productId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
