# Generated by Django 4.2.5 on 2025-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0010_coupangdailysales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangdailysales',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
