# Generated by Django 4.2.5 on 2025-02-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0011_alter_coupangdailysales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangitem',
            name='marketplace_vendor_item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupangitem',
            name='rocket_vendor_item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
