# Generated by Django 4.2.5 on 2025-02-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0012_alter_coupangitem_marketplace_vendor_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupangdailysales',
            name='option_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option Name'),
        ),
        migrations.AddField(
            model_name='coupangdailysales',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='coupangdailysales',
            name='net_sales_amount',
            field=models.BigIntegerField(verbose_name='Net Sales Amount'),
        ),
        migrations.AlterField(
            model_name='coupangdailysales',
            name='total_cancellation_amount',
            field=models.BigIntegerField(verbose_name='Total Cancellation Amount'),
        ),
        migrations.AlterField(
            model_name='coupangdailysales',
            name='total_transaction_amount',
            field=models.BigIntegerField(verbose_name='Total Transaction Amount'),
        ),
    ]
