# Generated by Django 4.2.5 on 2025-02-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0013_coupangdailysales_option_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('delivery_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='구분(delivery_label)')),
                ('sold_items', models.IntegerField(default=0, verbose_name='판매수량(sold_items)')),
                ('ads_sold_items', models.IntegerField(default=0, verbose_name='광고판매수량(ads_sold_items)')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='전환률(conversion_rate)')),
                ('total_transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='매출(total_transaction_amount)')),
                ('ads_total_transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='광고집행매출(ads_total_transaction_amount)')),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='광고집행비(ad_spend)')),
                ('net_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='순이익금(net_sales_amount)')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='상품명(product_name)')),
                ('option_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션명(option_name)')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='item_name')),
                ('sku_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='sku_id')),
                ('external_vendor_sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션코드(external_vendor_sku)')),
                ('item_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='item_id')),
            ],
        ),
        migrations.CreateModel(
            name='CoupangAdsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('ad_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Type')),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campaign ID')),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campaign Name')),
                ('ad_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Group')),
                ('executed_product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Executed Product Name')),
                ('executed_option_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Executed Option ID')),
                ('converting_product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Converting Product Name')),
                ('converting_option_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Converting Option ID')),
                ('ad_placement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Placement')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ad Spend')),
                ('ctr', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='CTR (Click-Through Rate)')),
                ('orders', models.IntegerField(default=0, verbose_name='Orders')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Sold Quantity')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Sales Amount')),
                ('roas', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='ROAS')),
            ],
        ),
    ]
