# Generated by Django 4.2.5 on 2025-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0015_coupangadsreport_option_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupangadsreport',
            constraint=models.UniqueConstraint(fields=('date', 'converting_option_id', 'impressions', 'clicks', 'ad_spend', 'orders'), name='unique_report_by_date_option_imp_click_spend_orders'),
        ),
    ]
