# Generated by Django 4.2.5 on 2025-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0019_alter_adsreport_ad_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsreport',
            name='ad_spend',
            field=models.IntegerField(default=0, verbose_name='광고집행비(ad_spend)'),
        ),
        migrations.AlterField(
            model_name='adsreport',
            name='ads_total_transaction_amount',
            field=models.IntegerField(default=0, verbose_name='광고집행매출(ads_total_transaction_amount)'),
        ),
        migrations.AlterField(
            model_name='adsreport',
            name='net_sales_amount',
            field=models.IntegerField(default=0, verbose_name='순이익금(net_sales_amount)'),
        ),
        migrations.AlterField(
            model_name='adsreport',
            name='total_transaction_amount',
            field=models.IntegerField(default=0, verbose_name='매출(total_transaction_amount)'),
        ),
    ]
