# Generated by Django 4.2.5 on 2025-02-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0020_alter_adsreport_ad_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangadsreport',
            name='ad_spend',
            field=models.IntegerField(default=0, verbose_name='Ad Spend'),
        ),
        migrations.AlterField(
            model_name='coupangadsreport',
            name='sales_amount',
            field=models.IntegerField(default=0, verbose_name='Sales Amount'),
        ),
    ]
