# Generated by Django 4.2.5 on 2025-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0021_alter_coupangadsreport_ad_spend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(max_length=100, unique=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('rocket_cost', models.IntegerField(default=0)),
                ('traffic_cost', models.IntegerField(default=0)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('ad_cost', models.IntegerField(default=0)),
                ('ad_cost_01', models.IntegerField(default=0)),
                ('ad_cost_02', models.IntegerField(default=0)),
                ('ad_cost_03', models.IntegerField(default=0)),
                ('discount_cost', models.IntegerField(default=0)),
                ('coupon_cost', models.IntegerField(default=0)),
                ('etc_cost_01', models.IntegerField(default=0)),
                ('etc_cost_02', models.IntegerField(default=0)),
                ('etc_cost_03', models.IntegerField(default=0)),
                ('inout_cost', models.IntegerField(default=0)),
                ('storage_cost', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cost_model',
            },
        ),
    ]
