# Generated by Django 4.2.5 on 2025-02-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0023_purchasecost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecost',
            name='option_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasecost',
            name='sku_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
