# Generated by Django 4.2.5 on 2025-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0024_alter_purchasecost_option_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecost',
            name='sku_id',
            field=models.CharField(max_length=100),
        ),
    ]
