# Generated by Django 4.2.5 on 2025-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0025_alter_purchasecost_sku_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='naverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(help_text='상품ID(originProductNo)', max_length=50)),
                ('skuID', models.CharField(help_text='SKUID(optionCombinations.id)', max_length=50, unique=True)),
                ('optioncode', models.CharField(blank=True, help_text='옵션코드(optionCombinations.sellerManagerCode)', max_length=100)),
                ('delivery_label', models.CharField(default='판매자배송', help_text='구분(판매자배송)', max_length=20)),
                ('itemName', models.CharField(help_text='상품명(name)', max_length=200)),
                ('option_name', models.CharField(blank=True, help_text='옵션명(optionCombinations.optionName1)', max_length=200)),
                ('product_price', models.IntegerField(help_text='정가(discountedPrice)')),
                ('option_price', models.IntegerField(default=0, help_text='옵션가(optionCombinations.price)')),
                ('account_name', models.CharField(help_text='브랜드(account_name)', max_length=100)),
                ('market_fee', models.FloatField(default=0.04, help_text='마켓수수료(4%)')),
                ('sale_price', models.IntegerField(default=0, help_text='판매가(product_price + option_price)')),
                ('profit', models.IntegerField(default=0, help_text='개당이익금(sale_price - sale_price*market_fee)')),
            ],
        ),
    ]
