# Generated by Django 4.2.5 on 2025-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0026_naveritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.CharField(help_text='주문ID(productOrder.productOrderId)', max_length=50)),
                ('product_name', models.CharField(help_text='상품명(productOrder.productName)', max_length=200)),
                ('product_id', models.CharField(help_text='상품ID(productOrder.productOrderId)', max_length=50)),
                ('option_name', models.CharField(blank=True, help_text='옵션명(productOrder.productOption)', max_length=200)),
                ('option_id', models.CharField(blank=True, help_text='옵션ID(productOrder.optionCode)', max_length=100)),
                ('sales_qty', models.IntegerField(default=0, help_text='결제수량(productOrder.quantity)')),
                ('sales_revenue', models.IntegerField(default=0, help_text='결제금액(productOrder.productDiscountAmount)')),
                ('refunded_qty', models.IntegerField(default=0, help_text='환불수량(productOrder.quantity)')),
                ('refunded_revenue', models.IntegerField(default=0, help_text='환불금액(productOrder.productDiscountAmount)')),
            ],
        ),
    ]
