# Generated by Django 4.2.5 on 2025-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0027_naverdailysales'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverdailysales',
            name='date',
            field=models.CharField(default=0, help_text='날짜(left(orderDate,10))', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naverdailysales',
            name='store',
            field=models.CharField(default=0, help_text='스토어(account_name)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naverdailysales',
            name='order_ID',
            field=models.CharField(help_text='주문ID(productOrder.productOrderId)', max_length=50, unique=True),
        ),
    ]
