# Generated by Django 4.2.5 on 2025-02-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0028_naverdailysales_date_naverdailysales_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverdailysales',
            name='market_fee',
            field=models.IntegerField(default=0, help_text='마켓수수료(paymentCommission + knowledgeShoppingSellingInterlockCommission)'),
        ),
    ]
