# Generated by Django 4.2.5 on 2025-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0029_naverdailysales_market_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverdailysales',
            name='optioncode',
            field=models.CharField(blank=True, help_text='옵션코드(optionCombinations.sellerManagerCode)', max_length=100),
        ),
    ]
