# Generated by Django 4.2.5 on 2025-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0030_naverdailysales_optioncode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverAdsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('ad_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Type')),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campaign ID')),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campaign Name')),
                ('ad_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Group')),
                ('executed_product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Executed Product Name')),
                ('executed_option_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Executed Option ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name')),
                ('option_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='option_name')),
                ('converting_product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Converting Product Name')),
                ('converting_option_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Converting Option ID')),
                ('ad_placement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Placement')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('ctr', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='CTR (Click-Through Rate)')),
                ('orders', models.IntegerField(default=0, verbose_name='Orders')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Sold Quantity')),
                ('sales_amount', models.IntegerField(default=0, verbose_name='Sales Amount')),
                ('ad_spend', models.IntegerField(default=0, verbose_name='Ad Spend')),
                ('roas', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='ROAS')),
            ],
        ),
        migrations.AlterField(
            model_name='naverdailysales',
            name='optioncode',
            field=models.CharField(blank=True, help_text='옵션코드(optionManageCode)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='naveradsreport',
            constraint=models.UniqueConstraint(fields=('date', 'converting_option_id', 'impressions', 'clicks', 'ad_spend', 'orders'), name='unique_naver_report_by_date_option_imp_click_spend_orders'),
        ),
    ]
