# Generated by Django 4.2.5 on 2025-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0033_naveritem_channelproductid'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverdailysales',
            name='originalProductId',
            field=models.CharField(default=1234, help_text='상품ID(productOrder.originalProductId)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naverdailysales',
            name='product_id',
            field=models.CharField(help_text='상품ID(productOrder.productId)', max_length=50),
        ),
    ]
