# Generated by Django 4.2.5 on 2025-02-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0034_naverdailysales_originalproductid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverAdReport',
            fields=[
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('ad_group_id', models.CharField(db_index=True, max_length=50)),
                ('ad_id', models.CharField(db_index=True, max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id_of_mall', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_image_url', models.URLField(blank=True, null=True)),
                ('impression', models.PositiveIntegerField(blank=True, null=True)),
                ('click', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conversion_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sales_by_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('ad_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ads_total_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ad_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('roas', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ad_sales_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='NaverAdConversionDetail',
        ),
        migrations.DeleteModel(
            name='NaverAdDetail',
        ),
        migrations.DeleteModel(
            name='NaverAdgroup',
        ),
        migrations.DeleteModel(
            name='NaverCampaign',
        ),
        migrations.DeleteModel(
            name='NaverShoppingProduct',
        ),
    ]
