# Generated by Django 4.2.5 on 2025-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0035_naveradreport_delete_naveradconversiondetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naveradreport',
            name='ctr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='naveradreport',
            name='customer_id',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
