# Generated by Django 4.2.5 on 2025-02-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0036_naveradreport_ctr_naveradreport_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverAdShoppingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('ad_group_id', models.CharField(db_index=True, max_length=50)),
                ('ad_id', models.CharField(db_index=True, max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id_of_mall', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='naveradreport',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='naveradreport',
            name='product_id_of_mall',
        ),
        migrations.RemoveField(
            model_name='naveradreport',
            name='product_image_url',
        ),
        migrations.RemoveField(
            model_name='naveradreport',
            name='product_name',
        ),
    ]
