# Generated by Django 4.2.5 on 2025-02-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0037_naveradshoppingproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaverAdsReport',
        ),
    ]
