# Generated by Django 4.2.5 on 2025-03-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0038_delete_naveradsreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='naveradreport',
            unique_together={('date', 'ad_group_id', 'ad_id', 'impression', 'click', 'cost', 'conversion_count', 'sales_by_conversion')},
        ),
    ]
