# Generated by Django 4.2.5 on 2025-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0039_alter_naveradreport_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverPurchaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=100)),
                ('option_code', models.CharField(blank=True, max_length=100, null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('purchasing_price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'naver_purchase_cost',
            },
        ),
    ]
