# Generated by Django 5.1.6 on 2025-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0040_naverpurchasecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='naveradreport',
            name='product_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
