# Generated by Django 5.1.6 on 2025-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0041_naveradreport_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naveradreport',
            name='product_category',
        ),
        migrations.AddField(
            model_name='naveradshoppingproduct',
            name='category_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
