# Generated by Django 4.2.5 on 2024-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0002_chatmessage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
