# Generated by Django 4.2.5 on 2025-01-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0005_remove_chatmessage_nickname_chatroom_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
