# Generated by Django 4.2.5 on 2025-01-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs_management', '0006_delete_chatmessage_delete_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupangOrderSheet',
            fields=[
                ('order_id', models.BigIntegerField(help_text='orderId (주문번호)')),
                ('shipment_box_id', models.BigIntegerField(help_text='shipmentBoxId', primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_price', models.IntegerField(blank=True, null=True)),
                ('remote_price', models.IntegerField(blank=True, null=True)),
                ('remote_area', models.BooleanField(default=False)),
                ('parcel_print_message', models.CharField(blank=True, max_length=255, null=True)),
                ('split_shipping', models.BooleanField(default=False)),
                ('able_split_shipping', models.BooleanField(default=False)),
                ('orderer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('orderer_safenum', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_safenum', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_addr1', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_addr2', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('in_transit_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('refer', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_items', models.JSONField(blank=True, help_text='orderItems 배열 통째로 저장', null=True)),
                ('representative_image', models.URLField(blank=True, null=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('gpt_summary', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '쿠팡 발주서',
                'verbose_name_plural': '쿠팡 발주서 목록',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('inquiry_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at_utc', models.DateTimeField(blank=True, help_text='문의 생성시각(UTC 변환 or local parsing)', null=True)),
                ('answered', models.BooleanField(default=False)),
                ('answer_content', models.TextField(blank=True, null=True)),
                ('representative_image', models.URLField(blank=True, null=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('gpt_summary', models.TextField(blank=True, null=True)),
                ('order_ids', models.TextField(blank=True, help_text="쿠팡 문의에서 사용. e.g. '[29100091940290]'", null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '통합문의',
                'verbose_name_plural': '통합문의 목록',
                'unique_together': {('platform', 'inquiry_id')},
            },
        ),
    ]
