# Generated by Django 4.2.5 on 2025-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='store_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
