# Generated by Django 4.2.5 on 2025-01-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0008_inquiry_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='answer_updated_at',
            field=models.DateTimeField(blank=True, help_text='답변 수정시간', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='최초 답변시간', null=True),
        ),
    ]
