# Generated by Django 4.2.5 on 2025-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0009_inquiry_answer_updated_at_inquiry_answered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
