# Generated by Django 4.2.5 on 2025-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0010_alter_inquiry_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='seller_product_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
