# Generated by Django 4.2.5 on 2025-01-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0011_inquiry_seller_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='gpt_confidence_score',
            field=models.FloatField(blank=True, help_text='GPT가 생성한 답변에 대한 신뢰도, 0~1 등', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='gpt_recommendation_1',
            field=models.TextField(blank=True, help_text='AI가 생성한 추천답변 #1', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='gpt_recommendation_2',
            field=models.TextField(blank=True, help_text='AI가 생성한 추천답변 #2', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='gpt_used_answer_index',
            field=models.IntegerField(blank=True, help_text='실제 채택된 GPT 답변 인덱스(1,2 등)', null=True),
        ),
    ]
