# Generated by Django 4.2.5 on 2025-01-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0013_centerinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerinquiry',
            name='content',
        ),
        migrations.RemoveField(
            model_name='centerinquiry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='centerinquiry',
            name='title',
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='answer_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='answer_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='created_at_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='gpt_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='gpt_recommendation_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='gpt_recommendation_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='gpt_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='gpt_used_answer_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='inquiry_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='inquiry_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='inquiry_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='option_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='orderId01',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='orderId02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='representative_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centerinquiry',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
