# Generated by Django 4.2.5 on 2025-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_management', '0014_remove_centerinquiry_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerinquiry',
            name='inquiry_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centerinquiry',
            name='partner_transfer_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
