# Generated by Django 5.1.4 on 2024-12-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_process', '0006_alter_returnitem_return_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='product_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
