"""
Django settings for piaarlab project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# ALLOWED_HOSTS = [
#     'piaarlab.store', 
#     'www.piaarlab.store', 
#     '34.64.123.206', 
#     '127.0.0.1', 
#     'localhost'
# ]

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://piaarlab.store",
    "https://www.piaarlab.store",  # www도 사용 중이라면
    'https://d607-211-243-19-247.ngrok-free.app',

]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
SERVICE_ACCOUNT_FILE = config('SERVICE_ACCOUNT_FILE', default=None)

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n4(7c9kkttt1r%pq%aa=a!!+^w9)3^9z@8vc8=(n9o()*+27n3'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True



# Application definition

INSTALLED_APPS = [
    'return_process',  # 이 줄을 추가하세요
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'delayed_management',  # 새로 추가
    'cs_management.apps.CsManagementConfig',  # 또는 'cs_management'
    'webhook',


]

CRONJOBS = [
    ('0 8 * * *', 'django.core.management.call_command', ['update_returns_command'])
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'piaarlab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'piaarlab.wsgi.application'

SOLAPI_ACCOUNTS = [
    {
        'name': '기본계정',
        'api_key': config('SOLAPI_API_KEY', default=None),
        'api_secret': config('SOLAPI_API_SECRET', default=None),
        'sender': config('SOLAPI_SENDER', default=None),
    },
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'return_process.CustomUser'

# settings.py

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '반품목록'
LOGOUT_REDIRECT_URL = 'login'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'level': 'DEBUG',  # 여기서 DEBUG로 설정
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'piaarlab.log',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'return_process': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # 디버그 레벨로 설정
            'propagate': False,
        },
               # ↓↓↓ [추가] delayed_management 로거 설정 ↓↓↓
        'delayed_management': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

# 이미 'django.middleware.security.SecurityMiddleware'가 설치되어 있다면,
# 아래 항목들을 함께 설정해줍니다.

# 2-1) HTTPS로 리다이렉트
SECURE_SSL_REDIRECT = False

# 2-2) HSTS(HTTP Strict Transport Security) 설정 (선택)
SECURE_HSTS_SECONDS = 31536000    # 1년(초 단위)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 2-3) 쿠키 보안 설정
SESSION_COOKIE_SECURE = True      # HTTPS를 통해서만 쿠키 전송
CSRF_COOKIE_SECURE = True         # HTTPS를 통해서만 CSRF 쿠키 전송