# Generated by Django 5.1.6 on 2025-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0004_alter_traffic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='type',
            field=models.CharField(blank=True, choices=[('단일', '단일'), ('원부', '원부')], max_length=100, null=True, verbose_name='단일,원부'),
        ),
    ]
