# Generated by Django 5.1.6 on 2025-03-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0006_task_single_product_link_task_single_product_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_management.product'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='로딩중', max_length=20),
        ),
    ]
