# Generated by Django 5.1.6 on 2025-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0010_keywordranking_search_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmonitoring',
            name='main_keyword1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rankingmonitoring',
            name='main_keyword1_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingmonitoring',
            name='main_keyword2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rankingmonitoring',
            name='main_keyword2_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingmonitoring',
            name='main_keyword3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rankingmonitoring',
            name='main_keyword3_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
