# Generated by Django 5.1.6 on 2025-03-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0015_navermarketingcost'),
        ('traffic_management', '0020_merge_20250310_1617'),
    ]

    operations = [
    ]
