# Generated by Django 5.1.6 on 2025-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0024_alter_navermarketingcost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='store_name',
            field=models.CharField(default='', max_length=255, verbose_name='스토어명'),
        ),
    ]
