# Generated by Django 5.1.6 on 2026-02-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0026_alter_keywordranking_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='campaign_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cycle_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
