# Generated by Django 4.2.5 on 2025-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproductoption',
            name='option_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
