# Generated by Django 4.2.5 on 2025-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='solapi_group_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
