# Generated by Django 4.2.5 on 2025-01-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0002_alter_externalproductoption_option_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductoption',
            name='seller_tool_stock',
            field=models.IntegerField(default=0),
        ),
    ]
