# Generated by Django 4.2.5 on 2024-12-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0002_optionstoremapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(max_length=100)),
                ('order_option_name', models.CharField(blank=True, max_length=255)),
                ('exchangeable_options', models.TextField(blank=True)),
                ('restock_date', models.DateField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=100)),
                ('changed_option', models.CharField(blank=True, max_length=255)),
                ('waiting', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
