# Generated by Django 4.2.5 on 2024-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0003_delayedshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='order_number_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='order_number_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='order_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='seller_option_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='seller_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
