# Generated by Django 4.2.5 on 2025-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0003_externalproductoption_seller_tool_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionplatformdetail',
            name='seller_tool_stock',
            field=models.IntegerField(default=0),
        ),
    ]
