# Generated by Django 4.2.5 on 2025-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0003_alter_delayedshipment_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofstockmapping',
            name='out_of_stock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
