# Generated by Django 4.2.5 on 2025-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0004_outofstockmapping_out_of_stock_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionplatformdetail',
            name='out_of_stock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
