# Generated by Django 4.2.5 on 2025-01-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0004_optionplatformdetail_seller_tool_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfStockMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(db_index=True, max_length=100)),
                ('order_product_name', models.CharField(blank=True, max_length=200)),
                ('order_option_name', models.CharField(blank=True, max_length=200)),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('seller_product_name', models.CharField(blank=True, max_length=200)),
                ('seller_option_name', models.CharField(blank=True, max_length=200)),
                ('expected_date', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
