# Generated by Django 4.2.5 on 2024-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0004_delayedshipment_order_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedorder',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
