# Generated by Django 4.2.5 on 2025-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0005_optionplatformdetail_out_of_stock_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayedshipment',
            name='send_type',
            field=models.CharField(choices=[('none', '미발송'), ('sms', '문자'), ('kakao', '알림톡'), ('webhook', '대기중'), ('dupli', '중복')], default='NONE', help_text='문자(SMS), 알림톡(KAKAO), 혹은 미전송(NONE) 등', max_length=10),
        ),
    ]
