# Generated by Django 4.2.5 on 2024-12-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0005_delayedorder_quantity_delayedshipment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayedshipment',
            name='changed_option',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='exchangeable_options',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='order_number_1',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='order_number_2',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='seller_option_name',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='seller_product_name',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='delayedshipment',
            name='waiting',
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='status',
            field=models.CharField(choices=[('purchase', '구매된상품들'), ('shipping', '배송중'), ('arrived', '도착완료'), ('document', '서류작성'), ('loading', '선적중')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='delayedshipment',
            name='option_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
