# Generated by Django 4.2.5 on 2025-01-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0005_outofstockmapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalproductoption',
            unique_together={('product', 'option_id')},
        ),
    ]
