# Generated by Django 4.2.5 on 2025-01-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0006_alter_delayedshipment_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionmapping',
            name='base_sale_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
