# Generated by Django 4.2.5 on 2025-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0006_alter_externalproductoption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductoption',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
