# Generated by Django 4.2.5 on 2025-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0007_optionmapping_base_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionmapping',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
