# Generated by Django 4.2.5 on 2025-01-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0007_externalproductoption_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionplatformdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optionplatformdetail',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
