# Generated by Django 4.2.5 on 2025-01-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0008_optionmapping_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100, verbose_name='플랫폼명')),
                ('representative_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='대표이미지')),
                ('product_id', models.CharField(max_length=50, verbose_name='상품ID')),
                ('option_id', models.CharField(max_length=50, unique=True, verbose_name='옵션ID')),
                ('option_id_stock', models.IntegerField(default=0, verbose_name='옵션ID재고')),
                ('seller_tool_stock', models.IntegerField(default=0, verbose_name='셀러툴재고')),
                ('expected_restock_date', models.DateTimeField(blank=True, null=True, verbose_name='예상날짜')),
                ('order_product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='주문상품명')),
                ('order_option_name_01', models.CharField(blank=True, max_length=200, null=True, verbose_name='주문옵션명01')),
                ('order_option_name_02', models.CharField(blank=True, max_length=200, null=True, verbose_name='주문옵션명02')),
                ('seller_product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='셀러툴상품명')),
                ('seller_option_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='셀러툴옵션명')),
                ('option_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션코드')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='정가')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='할인가')),
                ('add_option_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='추가옵션가')),
                ('out_of_stock_at', models.DateTimeField(blank=True, null=True, verbose_name='품절처리시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트시간')),
            ],
            options={
                'verbose_name': '재고품절',
                'verbose_name_plural': '재고품절 목록',
            },
        ),
    ]
