# Generated by Django 4.2.5 on 2024-12-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0008_alter_delayedshipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='expected_restock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
