# Generated by Django 4.2.5 on 2024-12-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0009_delayedshipment_expected_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionmapping',
            name='option_code',
            field=models.CharField(max_length=100),
        ),
    ]
