# Generated by Django 4.2.5 on 2025-01-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0009_outofstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofstock',
            name='status',
            field=models.IntegerField(default=0, verbose_name='표시상태'),
        ),
    ]
