# Generated by Django 4.2.5 on 2024-12-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0010_alter_productoptionmapping_option_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayedshipment',
            name='option_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='optionstoremapping',
            name='option_code',
            field=models.CharField(max_length=100),
        ),
    ]
