# Generated by Django 4.2.5 on 2025-01-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0010_outofstock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outofstock',
            name='add_option_price',
            field=models.IntegerField(default=0, verbose_name='추가옵션가'),
        ),
        migrations.AlterField(
            model_name='outofstock',
            name='original_price',
            field=models.IntegerField(default=0, verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='outofstock',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='할인가'),
        ),
    ]
