# Generated by Django 4.2.5 on 2024-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0011_alter_delayedshipment_option_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
