# Generated by Django 4.2.5 on 2024-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0012_delayedshipment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='send_status',
            field=models.CharField(choices=[('none', '발송 전'), ('pending', '대기'), ('success', '성공'), ('failed', '실패')], default='none', help_text='발송 전(none), 대기(pending), 성공(success), 실패(failed)', max_length=10),
        ),
        migrations.AddField(
            model_name='delayedshipment',
            name='send_type',
            field=models.CharField(choices=[('none', '미발송'), ('sms', '문자'), ('kakao', '알림톡')], default='none', help_text='문자(sms), 알림톡(kakao), 미발송(none)', max_length=10),
        ),
    ]
