# Generated by Django 4.2.5 on 2024-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0013_delayedshipment_send_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayedshipment',
            name='send_status',
            field=models.CharField(choices=[('none', '발송 전'), ('pending', '대기'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='delayedshipment',
            name='send_type',
            field=models.CharField(choices=[('none', '미발송'), ('sms', '문자'), ('kakao', '알림톡')], default='none', max_length=10),
        ),
    ]
