# Generated by Django 4.2.5 on 2024-12-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0016_delayedshipmentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipmentgroup',
            name='shipments',
            field=models.ManyToManyField(related_name='shipment_groups', to='delayed_management.delayedshipment'),
        ),
    ]
