# Generated by Django 4.2.5 on 2024-12-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0017_delayedshipmentgroup_shipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='flow_status',
            field=models.CharField(choices=[('pre_send', '발송전'), ('sent', '발송완료'), ('confirmed', '확인완료'), ('shipped', '출고완료')], default='pre_send', max_length=20),
        ),
    ]
