# Generated by Django 4.2.5 on 2024-12-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayed_management', '0018_delayedshipment_flow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedshipment',
            name='changed_option_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
